services:
  db:
    image: postgres:18-alpine
    container_name: risikovurdering-db
    environment:
      POSTGRES_DB: risikovurdering
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: demo-passord
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app_user -d risikovurdering"]
      interval: 3s
      timeout: 3s
      retries: 30

  # backend:
  #   build:
  #     context: ./backend
  #   container_name: risikovurdering-backend
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   environment:
  #     # NB: db er service-navn i compose-nettverket
  #     DB_JDBC_URL: jdbc:postgresql://db:5432/risikovurdering
  #     DB_USER: app_user
  #     DB_PASSWORD: demo-passord

  #     # Hvis appen din st√∏tter PORT (anbefalt)
  #     PORT: "4001"
  #     # Hvis du har host-binding i config, sett den til 0.0.0.0
  #     HOST: "0.0.0.0"
  #   ports:
  #     - "4001:4001"

  # frontend:
  #   build:
  #     context: ./frontend
  #   container_name: risikovurdering-frontend
  #   environment:
  #     BACKEND_INTERNAL_URL: http://backend:4001
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - backend

volumes:
  db_data:
