ktor:
    application:
        modules:
            - no.storme.risikostyring.ApplicationKt.module
    deployment:
        port: 4001
postgres:
  url: "jdbc:postgresql://localhost/default"
  user: username
  password: password