ktor:
    application:
        modules:
            - no.storme.risikostyring.ApplicationKt.module
    deployment:
        host: 0.0.0.0
        port: 4001
postgres:
  url: "jdbc:postgresql://localhost/default"
  user: username
  password: password